# Generated by Django 5.2.8 on 2026-10-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("app_name", models.CharField(db_index=True, max_length=150)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("extra", models.JSONField(blank=True, null=True)),
                ("trace", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["app_name", "level", "created_at"],
                        name="logs_applog_app_nam_9f2088_idx",
                    )
                ],
            },
        ),
    ]
