{{- if not .Values.secrets.externalSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django-base-app.fullname" . }}-secrets
  labels:
    {{- include "django-base-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.values }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}

