{{- if .Values.beat.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django-base-app.fullname" . }}-beat
  labels:
    {{- include "django-base-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: beat
spec:
  replicas: {{ .Values.beat.replicaCount }}
  selector:
    matchLabels:
      {{- include "django-base-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: beat
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "django-base-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: beat
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "django-base-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-beat
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- toYaml .Values.beat.command | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "django-base-app.fullname" . }}-config
            - secretRef:
                name: {{ default (printf "%s-secrets" (include "django-base-app.fullname" .)) .Values.secrets.externalSecretName }}
          resources:
            {{- toYaml .Values.beat.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

