{{- if .Values.flower.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-base-app.fullname" . }}-flower
  labels:
    {{- include "django-base-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: flower
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.flower.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "django-base-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: flower
{{- end }}

